SELECT USER_ID, NICKNAME, CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) AS 전체주소, INSERT(INSERT(TLNO, 8, 0, '-'), 4, 0, '-') AS 전화번호
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U
ON B.WRITER_ID = U.USER_ID
GROUP BY NICKNAME HAVING COUNT(*) >= 3
ORDER BY USER_ID DESC