SELECT APNT_NO, PT_NAME, P.PT_NO, D.MCDP_CD, DR_NAME, APNT_YMD
FROM (SELECT APNT_YMD, APNT_NO, PT_NO, MCDP_CD, MDDR_ID FROM APPOINTMENT 
     WHERE APNT_CNCL_YN = 'N'
     AND MCDP_CD = 'CS') A
JOIN DOCTOR D
ON A.MDDR_ID = D.DR_ID
JOIN PATIENT P
ON A.PT_NO = P.PT_NO
WHERE APNT_YMD LIKE '2022-04-13%'
ORDER BY APNT_YMD 