SELECT E.EMP_NO, E.EMP_NAME,
CASE WHEN AVG(SCORE) >= 96 THEN 'S'
WHEN AVG(SCORE) >= 90 THEN 'A'
WHEN AVG(SCORE) >= 80 THEN 'B'
WHEN AVG(SCORE) < 80 THEN 'C'
END AS GRADE,
CASE WHEN AVG(SCORE) >= 96 THEN SAL * 0.2
WHEN AVG(SCORE) >= 90 THEN SAL * 0.15
WHEN AVG(SCORE) >= 80 THEN SAL * 0.1
WHEN AVG(SCORE) < 80 THEN 0
END AS BONUS
FROM HR_DEPARTMENT D
JOIN HR_EMPLOYEES E ON D.DEPT_ID = E.DEPT_ID
JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
GROUP BY EMP_NO, EMP_NAME
ORDER BY E.EMP_NO